# Generated by Django 4.2.4 on 2023-08-29 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='caseategory',
            new_name='category',
        ),
    ]
