# Generated by Django 4.2.4 on 2023-09-06 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('ELECTRONIC', 'ELECTRONIC'), ('STATIONARY', 'STATIONARY'), ('HARDWARE', 'HARDWARE'), ('FOOD', 'FOOD'), ('ORNAMENTS', 'ORNAMENTS')], max_length=20, null=True),
        ),
    ]
