# Generated by Django 4.2.4 on 2023-09-07 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_alter_product_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='staff',
            new_name='costumer',
        ),
    ]
