# Generated by Django 4.2.4 on 2023-09-07 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_rename_staff_order_costumer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='product',
            new_name='name',
        ),
    ]
